name: channel3

on:
  # schedule:
  #   - cron: '20,50 * * * *'
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  channel3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' # Specify the Python version you need
    - name: Download FFmpeg
      run: |
        sudo apt update
        sudo apt install ffmpeg 
        ffmpeg -version

    - name: Download N_m3u8DL-RE and Stream
      run: |
        wget -O N_m3u8DL-RE.tar.gz https://github.com/nilaoda/N_m3u8DL-RE/releases/download/v0.3.0-beta/N_m3u8DL-RE_v0.3.0-beta_linux-x64_20241203.tar.gz
        tar -xzf N_m3u8DL-RE.tar.gz
        ./N_m3u8DL-RE --live-real-time-merge "https://aps12.playlist.live-video.net/v1/playlist/CoUGzD_r_UnWS385yaW6UyYwMrkfCQe9Y1L4T7WEQyuarPaERuIiokdPl0UYvLVBzz-W0JY4YIngxY9hoJnGIJCjZysZHNEZfPZmKmGxyrZUYBwYBDaO40wmG1hBX08O0z2-VPr-5xsUIZZU4qaiZ5Oo3mxPnrf_o1Nr0u2JuPDUXA8LaaJaJI7xg8wdrec75MKV4I-vZ_ZcChJu5eZf-60fjcqgWcCHb2DoPZdmsTt1BLxF1gQINDcCiown2BD76eTYc37GSnnkalldgSmfLnrsVURMEA1PD6WssDXbBOS3LrBuR2gmpeFuyhuSe8KeEKPVfQF9gDcJvPuH-vuJGEPQRLDppWDivPzSWSH1JAmUQFdLWcG3QqC6fgNzLFZJy3qnyMDv0Rx4c7PLz8-YHegIKVhzAFZ_voUIzoYxOPOsBscYjJVfHexJNW65t_DqItYaU5ARojQ_FcoW20kP5Ij1-C-ugUcBjkcca0bJax2A2qJiGLD6AZ9DodZPhijXX15u5wmLxW1SxTtIIdx_hj-BxS5UPN6E6STffaJmJj6Hhs2MpNo-Z3wuP6XlqHU6pPeqO6bczPin8F7g6ZfYgmYywV2YE1ohxRO4GYShJHV4yRotwW4jrlKcZGcscKw-ySWUbo1kBODPFnzcMQ-qcIsl0hua6ldtiS3UjkYZCUi57H26EzdL8SUSN5dqiA1sI92DhZaKXgVLqQD4YYicOr5DVYUsBV8ZXRVpRVAfWUuDq7Ce3yWsLtZVidb8q_ZmtwX8TBJDGer6hn333p2DZCmXNX_l3uYysTmgY-HoB7jrdDg72CTbzeCE69d2O-D8_qpnaj93uPp9ip55DDBs9bBwb6IMv3GEcHZbrIpr0KgoJBOKhyLE9V1dj_g-hwHoxno02BjKdZ3sAxaq3T3CQUFTT2tv9eGKZ8-gShqVloSdQYP90iCilD8qSxx2QzqMM_X7Vi7DlsM9Sw3ZtBdDLF2F5NcmdceRIiaz1ODScsP3xjPPnxnVfqzy7-sKpijHm65Y-ZYW0WsaDP7eIjcvvUmYKZhexSABKgl1cy13ZXN0LTIwpgw.m3u8" --save-name chunklist &
        # --live-keep-segments 
    
    - name: Run Python script
      run: |
        pip install requests
        pip install pywidevine
        python send_Telegram.py
      env:
        channel_id: "-1002290539654"
        bot_token: ${{ secrets.bot_token }}
