name: channel3

on:
  # schedule:
  #   - cron: '20,50 * * * *'
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  channel3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' # Specify the Python version you need
    - name: Download FFmpeg
      run: |
        sudo apt update
        sudo apt install ffmpeg 
        ffmpeg -version

    - name: Download N_m3u8DL-RE and Stream
      run: |
        wget -O N_m3u8DL-RE.tar.gz https://github.com/nilaoda/N_m3u8DL-RE/releases/download/v0.3.0-beta/N_m3u8DL-RE_v0.3.0-beta_linux-x64_20241203.tar.gz
        tar -xzf N_m3u8DL-RE.tar.gz
        ./N_m3u8DL-RE --live-real-time-merge "https://aps11.playlist.live-video.net/v1/playlist/CoUGTjExEnlIf8mzLYn_QNcpD-lzmpyvGW6-ErfzJ7h_60oLB7ylgGNxkYtdgxyoSbPYaqOoxpsmcZBti57GohRscaD-nysgFFGwWNkOHu63XeYN_Gc61JBOq0W0T3EULx2Ir3Vu9M5f6gaQnwG8t-ADIIWCpl9jSxaGptd3K2XGyJhJf50MY1KMPMVm1Y4KrJo3lTDQ8fAsHLhKORRBpdPCmJVFGSoFowGFziybhLkW_iVFgdeMaZTkLSmYIfnPRn1KHG6eGbHWhxb82eyr3yuaTeonoGKokdFbUhOCjbqRRWdtSkv6cE0GqjGRroq0Niltgz1j5it8PeGLwWz8Opf23f7wbpBNM7CJvJ-qBbOihRdk-RvTa0y1CNXEKG992JjRubg3ihcT02RxbAwi18oI9V8ZgMRBFnqYmDcHfm_Y1DOZmRuhKp00cruEV65HNcOXgL-tKd29i8MPL6cjwGNMGrzhTraHCqar46AHJyHxw9l31qdJsLshmXwKHrf6fbGtLTmRfBeMx1U1ityPzNjpJFOKuORwBGNRaOm9HTiqpXgagSn6yLtqzAaKrxGgMoyZ6Fqs0MBGOkRj-3z38ru1JHKIVZK3XVilECbzlliXcAlgLorLapqJqseE9C8lh6O1513fbM4wR77tb99WRKxnr9vzIUHkO34dQh0J5YsGqagi0Cx2Re-uerFCtJ_7wX_6Cn0jhs-k5u15s_sAiszLbzvuKvOOeoYuLetUfNT7tzUarMnYZER8LPm634Wgd5tmKPMRdsL500eNXdcuDsP6Ou9bkAvNM2AquKh_PaBD5aWyPMDHR1cjy4igEuaHZTmDHL4gfy3E7Sk1iCJbMD0vfhIyGI2C0wUN_gBQWaZzILjHtrwXAzG2BYPSXbUNVp2r14cpoOQ21PKwcqIQ1yjJU75rXgG4wmcJ2uncR5U4KTIdw_8lq8MOjS99hI_r0yeGI84tRhQaM4Ou1QHJxJpWN_NS0Vm3rKasVVjd8P6jElH7m5dVYk8ewfpx9ShciKWx-WLN6NgaDOu1Cu_vQ07U6ygkoiABKgl1cy13ZXN0LTIwpgw.m3u8" --save-name chunklist &
        # --live-keep-segments 
    
    - name: Run Python script
      run: |
        pip install requests
        pip install pywidevine
        python send_Telegram.py
      env:
        channel_id: "-1002290539654"
        bot_token: ${{ secrets.bot_token }}
